name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.1.0
      with:
        file: ./Dockerfile
        push: true
        tags: |
          alienengineer/cresce:latest
          alienengineer/cresce:1.0.0

    - name: Trigger Azure Deploy
      uses: muinmomin/webhook-action@v1.0.0
      with:
        url: ${{ secrets.AZURE_DEPLOY_WEBHOOK }}
